# Generated by Django 6.0 on 2026-01-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPRefModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=120, unique=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('isp', models.CharField(max_length=50)),
                ('org', models.CharField(max_length=50)),
                ('asn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('reload_count_in_a_clock', models.IntegerField(default=1)),
                ('time_tick_count', models.PositiveBigIntegerField(default=1)),
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytical.iprefmodel')),
            ],
        ),
        migrations.CreateModel(
            name='IPRequestMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('http_sec_ch_ua', models.TextField(blank=True, null=True)),
                ('query_string', models.TextField(blank=True, null=True)),
                ('request_type', models.CharField(blank=True, max_length=20, null=True)),
                ('request_data', models.TextField(blank=True, null=True)),
                ('fingerprint', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='analytical.iprefmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ip', 'fingerprint'), name='uniq_ip_meta_fingerprint')],
            },
        ),
    ]
