# Generated by Django 5.1.1 on 2025-01-26 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0011_alter_viewmodel_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatMapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('view', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical.viewmodel')),
            ],
        ),
    ]
