# Generated by Django 5.2.7 on 2026-01-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0012_heatmapdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=120, unique=True)),
            ],
        ),
    ]
