# Generated by Django 6.0 on 2026-01-16 15:41

import contents.models
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytical', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=40, null=True)),
                ('email', models.EmailField(default=None, max_length=40, null=True)),
                ('comment', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('view', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical.viewmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTypeModel',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('sub_tags', models.ManyToManyField(blank=True, related_name='content_types', to='tags.tagcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', contents.models.TurkishAutoSlugField(always_update=True, blank=True, editable=True, populate_from='title', unique=True)),
                ('show', models.BooleanField(default=True)),
                ('seo_description', models.CharField(max_length=500)),
                ('seo_image_url', models.TextField(blank=True, default=None, null=True)),
                ('seo_image_alt', models.TextField(blank=True, null=True)),
                ('text', models.TextField(help_text='use html')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, default=None, dimensions=768, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('language_type', models.CharField(choices=[('1', 'English'), ('2', 'Türkçe')], default='1', max_length=1)),
                ('custom_data', models.JSONField(blank=True, default=contents.models.get_default_custom_data, null=True)),
                ('demo_ref', models.URLField(blank=True, null=True)),
                ('demo_video_ref', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='content', to='contents.contentcommentmodel')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tagmodel')),
                ('view', models.ManyToManyField(blank=True, default=None, to='analytical.viewmodel')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.contenttypemodel')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
