# Generated by Django 5.2.7 on 2025-10-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_contentmodel_custom_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
