# Generated by Django 5.2.7 on 2025-12-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_contentmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='embedding',
            field=models.JSONField(blank=True, default=list, editable=False, null=True),
        ),
    ]
