# Generated by Django 5.2.7 on 2025-12-11 15:46

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_contentmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
