# Generated by Django 5.2.7 on 2025-12-17 01:16

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_contentmodel_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
