FROM python:3.12-slim
LABEL authors="seker"

RUN mkdir /app
WORKDIR /app


ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip
COPY requirements.txt  /app/
RUN pip install -r requirements.txt

COPY . /app/

EXPOSE 8000
CMD ["python", "manage.py", "test", "&&", "python", "manage.py", "runserver", "0.0.0.0:8000"]
