# Generated by Django 5.1.1 on 2025-01-22 09:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=75)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('instagram', models.URLField(blank=True, default='', null=True)),
                ('github', models.URLField(blank=True, default='', null=True)),
                ('twitter', models.URLField(blank=True, default='', null=True)),
                ('stackoverflow', models.URLField(blank=True, default='', null=True)),
                ('youtube', models.URLField(blank=True, default='', null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
