# Generated by Django 5.1.1 on 2025-01-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
