# Generated by Django 5.1.1 on 2025-01-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_testimonial_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='linkedin',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
