# Generated by Django 6.0 on 2026-01-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, default=None, null=True)),
                ('field_type', models.CharField(choices=[('1', 'MD'), ('2', 'List'), ('3', 'img'), ('4', 'text'), ('5', 'html')], default='1', max_length=2)),
                ('field_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NavbarItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('icon_position', models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End')], default=None, max_length=10)),
                ('display_text_on_hover_pc', models.BooleanField(default=True)),
                ('hide_text_on_pc', models.BooleanField(default=False)),
                ('hide_text_on_mobile', models.BooleanField(default=True)),
                ('navbar_item_position', models.CharField(choices=[('start', 'Start'), ('center', 'Center'), ('end', 'End')], max_length=10)),
                ('url_type', models.CharField(choices=[('hashtag', 'Hashtag'), ('internal', 'Internal'), ('external', 'External')], max_length=20)),
                ('internal_url', models.CharField(blank=True, max_length=255, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavbarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('items', models.ManyToManyField(to='pages.navbaritemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, default=None, null=True)),
                ('image_alt', models.TextField(blank=True, null=True)),
                ('disable_ceo', models.BooleanField(default=False)),
                ('context', models.ManyToManyField(blank=True, to='pages.contextfieldmodel')),
                ('view', models.ManyToManyField(blank=True, default=None, to='analytical.viewmodel')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
