# Generated by Django 5.1.1 on 2025-02-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatemodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
