# Generated by Django 5.1.1 on 2025-02-10 02:30

import projects.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificatemodel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateprovidermodel',
            name='slug',
            field=projects.models.TurkishAutoSlugField(always_update=True, blank=True, editable=True, populate_from='name', unique=True),
        ),
    ]
