# Generated by Django 5.1.1 on 2025-05-02 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwithme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmodel',
            name='meeting_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
