# Generated by Django 5.1.1 on 2025-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwithme', '0002_meetingmodel_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmodel',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
