# Generated by Django 5.2.7 on 2025-12-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwithme', '0004_chatlog_chatroom_delete_chathistory_chatlog_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='hash_stamp',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
