# Generated by Django 5.2.7 on 2025-12-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatwithme', '0005_chatroom_hash_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='extra_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
